backend:
  replicaCount: 2
  image:
    repository: captainyun/k8s-labs-todo-backend
    tag: v1.0
  service:
    type: NodePort
    port: 8080
    targetPort: 8080
    nodePort:
      enabled: true
      port: 30001
  cors_allowed_origins: http://localhost:3000

database:
  name: tododb
  user: todouser
  password: "todo1234"
  rootPassword: "root1234"
